repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer

  - repo: local
    hooks:
      - id: biome
        name: biome check
        entry: npx @biomejs/biome check --apply .
        language: system

      - id: dprint
        name: dprint fmt
        entry: npx dprint fmt
        args: ['--allow-no-files']
        language: system
